import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import BottomNavigation from "../components/navigation/BottomNavigation";
import PrimaryButton from "../components/buttons/PrimaryButton";
import Colors from "../constants/colors";
import { MoodId, moodConfigurations } from "../features/mood/moodRepository";
import { SavedMood, useMoodHistory } from "../features/mood/MoodHistoryContext";
import { useMoodQuote } from "../features/mood/useMoodQuote";

type Tab = "Today" | "Weekly" | "Monthly";
const moodList = Object.values(moodConfigurations);

export default function MoodScreen() {
  const router = useRouter(); const { savedMoods } = useMoodHistory(); const [tab, setTab] = useState<Tab>("Today"); const [selectedMood, setSelectedMood] = useState<MoodId>("angry"); useMoodQuote(selectedMood);
  return <SafeAreaView style={styles.screen} edges={["top"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.title}>Mood</Text><View style={styles.tabs}>{(["Today", "Weekly", "Monthly"] as Tab[]).map((item) => <Pressable key={item} accessibilityRole="tab" accessibilityState={{ selected: tab === item }} onPress={() => setTab(item)} style={[styles.tab, tab === item ? styles.activeTab : null]}><Text style={[styles.tabText, tab === item ? styles.activeTabText : null]}>{item}</Text></Pressable>)}</View>{tab === "Today" ? <TodayView selectedMood={selectedMood} onSelect={setSelectedMood} onSave={() => router.push(`/mood-result?mood=${selectedMood}`)} /> : null}{tab === "Weekly" ? <WeeklyView savedMoods={savedMoods} /> : null}{tab === "Monthly" ? <MonthlyView savedMoods={savedMoods} /> : null}</ScrollView><BottomNavigation activeTab="Mood" /></SafeAreaView>;
}
function TodayView({ selectedMood, onSelect, onSave }: { selectedMood: MoodId; onSelect: (id: MoodId) => void; onSave: () => void }) { return <View style={styles.today}><View><Text style={styles.question}>How are you feeling today?</Text><Text style={styles.subtitle}>Choose the mood that feels closest to how you feel right now.</Text></View><View style={styles.moodGrid}>{moodList.map((mood) => <Pressable key={mood.id} accessibilityRole="radio" accessibilityState={{ selected: selectedMood === mood.id }} onPress={() => onSelect(mood.id)} style={[styles.moodCard, { backgroundColor: mood.color }, selectedMood === mood.id ? styles.selectedMood : null]}><Text style={styles.moodEmoji}>{mood.emoji}</Text><Text style={styles.moodName}>{mood.label}</Text>{selectedMood === mood.id ? <View style={styles.check}><Text style={styles.checkText}>✓</Text></View> : null}</Pressable>)}</View><PrimaryButton title="Save Mood" onPress={onSave} style={styles.saveButton} /></View>; }
function WeeklyView({ savedMoods }: { savedMoods: SavedMood[] }) { const today = startOfDay(new Date()); const monday = new Date(today); monday.setDate(today.getDate() - ((today.getDay() + 6) % 7)); const history = weekMoods(savedMoods, monday); const moodValues = history.filter((mood): mood is MoodId => Boolean(mood)); const counts = moodValues.reduce<Record<MoodId, number>>((result, mood) => ({ ...result, [mood]: (result[mood] ?? 0) + 1 }), {} as Record<MoodId, number>); const frequent = (Object.keys(counts) as MoodId[]).sort((first, second) => counts[second] - counts[first])[0]; const message = !moodValues.length ? "No moods saved this week yet. Save a mood to start your weekly insight." : moodValues.length === 1 ? `You saved 1 mood this week: ${moodConfigurations[moodValues[0]].label}.` : `${moodValues.length} saved moods this week. ${moodConfigurations[frequent].label} was selected most often.`; return <View style={styles.report}><Text style={styles.question}>Your week in moods</Text><View style={styles.weekRow}>{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day, index) => <View key={day} style={styles.day}><Text style={styles.dayName}>{day}</Text><Text style={styles.historyEmoji}>{history[index] ? moodConfigurations[history[index]].emoji : ""}</Text></View>)}</View><View style={styles.insightCard}><Text style={styles.insightTitle}>Weekly insight</Text><Text style={styles.insightText}>{message}</Text></View></View>; }
function MonthlyView({ savedMoods }: { savedMoods: SavedMood[] }) { const now = new Date(); const firstDay = new Date(now.getFullYear(), now.getMonth(), 1).getDay(); const days = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate(); const cells = Array.from({ length: firstDay + days }, (_, index) => index < firstDay ? null : index - firstDay + 1); const moods = monthMoods(savedMoods, now); return <View style={styles.report}><Text style={styles.question}>{now.toLocaleDateString("en-US", { month: "long", year: "numeric" })}</Text><View style={styles.calendar}>{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <Text key={day} style={styles.calendarWeekday}>{day}</Text>)}{cells.map((date, index) => <View key={`${date}-${index}`} style={styles.calendarDay}>{date ? <><Text style={styles.date}>{date}</Text><Text style={styles.calendarEmoji}>{moods[date] ? moodConfigurations[moods[date]].emoji : ""}</Text></> : null}</View>)}</View></View>; }
function startOfDay(date: Date) { return new Date(date.getFullYear(), date.getMonth(), date.getDate()); }
function weekMoods(entries: SavedMood[], monday: Date) { const byDay: (MoodId | null)[] = Array(7).fill(null); entries.forEach((entry) => { const day = startOfDay(entry.loggedAt); const offset = Math.floor((day.getTime() - monday.getTime()) / 86_400_000); if (offset >= 0 && offset < 7 && !byDay[offset]) byDay[offset] = entry.mood; }); return byDay; }
function monthMoods(entries: SavedMood[], month: Date) { return entries.reduce<Record<number, MoodId>>((result, entry) => { const day = entry.loggedAt; if (day.getFullYear() === month.getFullYear() && day.getMonth() === month.getMonth() && !result[day.getDate()]) result[day.getDate()] = entry.mood; return result; }, {}); }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Colors.background }, content: { flexGrow: 1, paddingHorizontal: 12, paddingTop: 28, paddingBottom: 20, gap: 14 }, title: { color: Colors.darkPurple, fontSize: 29, fontWeight: "700" }, tabs: { flexDirection: "row", gap: 9 }, tab: { paddingHorizontal: 21, paddingVertical: 10, borderWidth: 1, borderColor: "#E8D9F5", borderRadius: 22, backgroundColor: Colors.white }, activeTab: { borderColor: "#D98CF6", backgroundColor: "#DE91F7" }, tabText: { color: "#A277C5", fontSize: 16 }, activeTabText: { color: Colors.darkPurple, fontWeight: "600" }, today: { gap: 14 }, question: { color: "#4D2C70", fontSize: 19, fontWeight: "600" }, subtitle: { marginTop: 4, color: "#A277C5", fontSize: 16, lineHeight: 23 }, moodGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, moodCard: { position: "relative", flexGrow: 1, flexBasis: "47%", height: 76, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 14, borderRadius: 24 }, selectedMood: { borderWidth: 2.5, borderColor: "#FF6C72" }, moodEmoji: { fontSize: 28 }, moodName: { flexShrink: 1, color: Colors.darkPurple, fontSize: 16, fontWeight: "600" }, check: { position: "absolute", top: 8, right: 8, width: 23, height: 23, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#F66C73" }, checkText: { color: Colors.white, fontWeight: "700" }, saveButton: { marginTop: 4 }, report: { gap: 23 }, weekRow: { flexDirection: "row", justifyContent: "space-between", padding: 18, borderRadius: 23, backgroundColor: Colors.white }, day: { alignItems: "center", gap: 10 }, dayName: { color: "#A27BB9", fontSize: 11 }, historyEmoji: { fontSize: 23 }, insightCard: { padding: 22, borderRadius: 24, backgroundColor: "#F0E2FF" }, insightTitle: { color: Colors.darkPurple, fontSize: 18, fontWeight: "700" }, insightText: { marginTop: 8, color: "#805A98", fontSize: 15, lineHeight: 23 }, calendar: { flexDirection: "row", flexWrap: "wrap", padding: 13, borderRadius: 23, backgroundColor: Colors.white }, calendarWeekday: { width: "14.285%", color: "#A27BB9", fontSize: 11, textAlign: "center" }, calendarDay: { width: "14.285%", height: 53, alignItems: "center", paddingTop: 8 }, date: { color: Colors.darkPurple, fontSize: 13 }, calendarEmoji: { marginTop: 3, fontSize: 17 }, });
