import React, { useState } from "react";
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import BottomNavigation from "../components/navigation/BottomNavigation";
import Colors from "../constants/colors";
import { useProfile } from "../features/profile/ProfileContext";
import { useAuth } from "../features/auth/AuthContext";

export default function ProfileScreen() {
  const router = useRouter(); const { profile } = useProfile(); const { signOut } = useAuth(); const [signingOut, setSigningOut] = useState(false); const initial = profile.name.trim().charAt(0).toUpperCase() || "A";
  const confirmSignOut = () => Alert.alert("Sign out?", "You will need to log in again to access your personalized data.", [{ text: "Cancel", style: "cancel" }, { text: "Sign Out", style: "destructive", onPress: () => void handleSignOut() }]);
  const handleSignOut = async () => { setSigningOut(true); try { await signOut(); router.replace("/login"); } finally { setSigningOut(false); } };
  return <SafeAreaView style={styles.screen} edges={["top"]}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Profile</Text><View style={styles.profileCard}><View style={styles.avatar}>{profile.avatarData ? <Image source={{ uri: profile.avatarData }} style={styles.avatarImage} /> : <Text style={styles.avatarText}>{initial}</Text>}</View><View style={styles.profileDetails}><Text style={styles.name}>{profile.name || "Your profile"}</Text><Text style={styles.email}>{profile.email}</Text><Pressable onPress={() => router.push("/edit-profile")}><Text style={styles.editLink}>Edit Profile →</Text></Pressable></View></View><Section title="ACCOUNT"><Row label="Edit Profile" onPress={() => router.push("/edit-profile")} /><Row label="Change Password" onPress={() => router.push("/forgot-password")} /></Section><Section title="MY WELLNESS"><Row label="Cycle Information" onPress={() => router.push("/cycle")} /><Row label="Mood History" onPress={() => router.push("/mood")} /></Section><Section title="PRIVACY"><Row label="Journal Privacy" onPress={() => Alert.alert("Private journal", "Journal entries are stored locally on this device for offline access.")} /><Row label="Data & Privacy" onPress={() => Alert.alert("Data & Privacy", "Your wellness profile is used only to personalize NAVYA predictions.")} /></Section><Pressable disabled={signingOut} onPress={confirmSignOut} style={[styles.signOut, signingOut && styles.signOutDisabled]}><Ionicons name="log-out-outline" size={21} color="#D4485B" /><Text style={styles.signOutText}>{signingOut ? "Signing out…" : "Sign Out"}</Text></Pressable></ScrollView><BottomNavigation activeTab="Profile" /></SafeAreaView>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.settingsCard}>{children}</View></View>; }
function Row({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Ionicons name="chevron-forward" size={22} color="#C6A1DE" /></Pressable>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Colors.background }, content: { paddingHorizontal: 15, paddingTop: 39, paddingBottom: 40, gap: 25 }, title: { color: Colors.darkPurple, fontSize: 28, fontWeight: "700" }, profileCard: { flexDirection: "row", alignItems: "center", gap: 21, padding: 26, borderWidth: 1, borderColor: "#E1C5FB", borderRadius: 30, backgroundColor: "#EBCFFF" }, avatar: { width: 80, height: 80, overflow: "hidden", alignItems: "center", justifyContent: "center", borderRadius: 40, backgroundColor: "#C978F1" }, avatarImage: { width: "100%", height: "100%" }, avatarText: { color: Colors.white, fontSize: 31, fontWeight: "700" }, profileDetails: { flex: 1 }, name: { color: Colors.darkPurple, fontSize: 23, fontWeight: "700" }, email: { marginTop: 5, color: "#A37ABC", fontSize: 17 }, editLink: { marginTop: 7, color: "#C86CF3", fontSize: 16, fontWeight: "600" }, section: { gap: 10 }, sectionTitle: { marginLeft: 4, color: "#C2A0D5", fontSize: 13, fontWeight: "700", letterSpacing: 1 }, settingsCard: { overflow: "hidden", borderWidth: 1, borderColor: "#E8D9F5", borderRadius: 28, backgroundColor: Colors.white }, row: { minHeight: 65, paddingHorizontal: 20, alignItems: "center", justifyContent: "space-between", flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#F0E7F8" }, rowLabel: { color: Colors.darkPurple, fontSize: 18 }, signOut: { minHeight: 56, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9, borderRadius: 19, backgroundColor: "#FFE8ED" }, signOutDisabled: { opacity: 0.6 }, signOutText: { color: "#D4485B", fontSize: 17, fontWeight: "700" } });
